#!/bin/bash
# how to use: ./md5_verifier.sh $HOME/Downloads/hashes.txt

current_folder=$(pwd)
cd $HOME/Downloads/

declare -a hashes_file
while IFS= read -r line || [[ -n "$line" ]]; do
    hashes_file+=("$line")
done < "$(dirname "$0")/$1" # Read the hashes from a file $1

files=("file_name1.war" "file_name3.war" "file_name3.zip")

for file in "${files[@]}"; do
  if [ -f "$file" ]; then
    current_hash=$(md5 "$file" | awk '{ print $4 }')
    for hash_file in "${hashes_file[@]}"; do
      hash_name=${hash_file%% *}
      hash_value=${hash_file#* }
      if [ "$current_hash" = "$hash_value" ] && [ "$file" = "$hash_name" ]; then
        echo -e "\033[0;32m :: ✓ $hash_name \033[0m"
        continue 2  # next file
      fi
    done
    echo -e "\033[0;31m :: x $file \033[0m"
  else
    echo -e "\033[0;31m :: The file $file is not in the Downloads folder.\033[0m"
  fi
done

cd "$current_folder"